i = int(input("Enter the first number: "))
j = int(input("Enter the second number: "))
print("The sum is: ", i + j)
print("The difference is: ", i - j)
print("The product is: ", i * j)
print("The quotient is: ", i / j)
print("The remainder is: ", i % j)
print("The floor division is: ", i // j)
print("The power is: ", i ** j)